# Generated by Django 4.1.7 on 2023-03-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
