# Generated by Django 4.1.7 on 2023-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
